machine:
  node:
    version: 8.9.4
  services:
   - docker

dependencies:
  post:
    - docker build -t https://github.com/stephenmulwa/DDD-AWS-APP.git .
test:
  post:
    - docker run -d -p 4200:4200 $https://github.com/stephenmulwa/DDD-AWS-APP.git; sleep 10
    
    - curl --retry 10 --retry-delay 5 localhost:4200 | grep "DDD AWS Heroes & Heroines"

    
